services:

    jackal_scheduler.process_executor:
        class: Jackal\Scheduler\Bundle\Processor\ProcessExecutor
        arguments: [@logger,%kernel.root_dir%]

    jackal_scheduler.processor:
        class: Jackal\Scheduler\Bundle\Processor\SchedulerProcessor
        arguments: [@jackal_scheduler.process_executor]
