services:

    jackal_scheduler.process.queue:
        class: Jackal\Scheduler\Bundle\Queue\CommandQueue
        arguments: [%kernel.root_dir%,@logger]
        tags:
         -  { name: monolog.logger, channel: scheduler }

    jackal_scheduler.command.manager:
        class: Jackal\Scheduler\Bundle\Manager\ScheduledCommandManager
        arguments: [@jackal_scheduler.process.queue]

    jackal_scheduler.command.scheduler:
        class: Jackal\Scheduler\Bundle\Command\SchedulerCommand
        arguments: [@jackal_scheduler.command.manager]
        tags:
         -  { name: console.command }

    jackal_scheduler.command.process_container:
        class: Jackal\Scheduler\Bundle\Command\ProcessContainerCommand
        arguments: [@logger,'%kernel.root_dir%']
        tags:
         -  { name: console.command }
         -  { name: monolog.logger, channel: scheduler }